# -*- coding: utf-8 -*-
"""
Pre6_DNN_GroupAware_Validation.py

Leakage-controlled DNN validation for the revised MC-CRoMD workflow.

Scientific policy
-----------------
1) Uses ONLY the already-created group-aware Train and Validation partitions.
2) NEVER loads or uses Test in this program.
3) Uses StandardScaled data generated by Pre4; no scaler is refitted here.
   Patch size 32 is read from Pre4 low-memory X.npy + Metadata.csv.gz storage.
4) Candidate feature configurations are pre-screened using ONLY the completed
   classical-model Screening results in Validation_Checkpoint.csv:
      - aggregate mean Validation Accuracy across all completed classical models
      - tie-break by mean Validation F1-Macro
      - final tie-break by smaller K (parsimony)
   The top-N unique (Feature_Method, K) configurations per scenario are then
   evaluated by the DNN.
5) DNN architecture and training hyperparameters are fixed a priori.
6) Each candidate configuration is repeated using prespecified random seeds
   (default: 42, 43, 44) to reduce dependence on a single stochastic run.
7) Final DNN configuration selection uses the MEAN validation performance
   across the prespecified seeds. No seed is cherry-picked.
8) Early stopping and model checkpointing monitor val_loss only.
9) Test remains locked for a separate final-test program after all model and
   feature-configuration decisions are frozen.
10) Per-sample validation predictions/probabilities, confusion matrices,
    histories, model files, and metadata are saved for reproducibility.

Default architecture
--------------------
Input
 -> Dense(128, ReLU)
 -> BatchNormalization
 -> Dropout(0.30)
 -> Dense(64, ReLU)
 -> BatchNormalization
 -> Dropout(0.20)
 -> Dense(32, ReLU)
 -> Binary: Dense(1, sigmoid)
    Multi-class: Dense(n_classes, softmax)

Optimizer       : Adam
Initial LR      : 0.001
Batch size      : 64
Max epochs      : 100
Early stopping  : monitor=val_loss, patience=15, restore_best_weights=True
Reduce LR       : monitor=val_loss, factor=0.5, patience=5, min_lr=1e-6
Checkpoint      : best val_loss
Selection       : mean Validation Accuracy, then mean Macro-F1, then smaller K
Seeds           : 42, 43, 44

Run example
-----------
python Pre6_DNN_GroupAware_Validation.py --patch-size 64
python Pre6_DNN_GroupAware_Validation.py --patch-size 128
python Pre6_DNN_GroupAware_Validation.py --patch-size 256
python Pre6_DNN_GroupAware_Validation.py --patch-size 32

IMPORTANT:
- Pre4, Pre5, and classical Pre6 Screening must already be complete for the
  requested patch size.
- This script intentionally refuses to read Test.
"""

from __future__ import annotations

# Determinism-related environment variables should be set before TensorFlow import.
import os
os.environ.setdefault("TF_DETERMINISTIC_OPS", "1")
os.environ.setdefault("PYTHONHASHSEED", "42")

import argparse
import gc
import json
import math
import platform
import random
import time
import warnings
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import sklearn
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.preprocessing import LabelEncoder, label_binarize

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


# =============================================================================
# Fixed experimental settings
# =============================================================================

SCENARIOS = ("Binary", "Three_Class", "Five_Class")
EXPECTED_CLASSICAL_MODELS = {
    "SVM_RBF",
    "SVM_Poly",
    "KNN",
    "RandomForest",
    "DecisionTree",
    "LogisticRegression",
    "SGD",
    "GaussianNB",
    "Voting",
}

TARGET_COLUMN = "label"
SOURCE_VARIANT = "StandardScaled"

# Spyder-friendly default. Change only this value to run another patch size.
PATCH_SIZE = 32

DEFAULT_TOP_N = 3
DEFAULT_SEEDS = (42, 43, 44)
DEFAULT_MAX_HOURS = 9.0

DENSE_UNITS = (128, 64, 32)
DROPOUT_RATES = (0.30, 0.20)
INITIAL_LEARNING_RATE = 1e-3
BATCH_SIZE = 64
MAX_EPOCHS = 100

EARLY_STOPPING_PATIENCE = 15
REDUCE_LR_FACTOR = 0.5
REDUCE_LR_PATIENCE = 5
MIN_LEARNING_RATE = 1e-6

PRIMARY_SELECTION_METRIC = "Mean_Validation_Accuracy"
SECONDARY_SELECTION_METRIC = "Mean_Validation_F1_Macro"

METADATA_COLUMNS = {
    "ImgName",
    "FileName",
    "ImagePath",
    "ClassName",
    "label",
    "SourceGroupID",
    "PatchSize",
    "ImageWidth",
    "ImageHeight",
    "ImageSHA256",
    "Split",
    "split",
    "stem",
    "filename",
    "tissue",
    "group_id",
    "local_cluster_label",
    "LC25000_ClassName",
    "LC25000_FileName",
    "LC25000_Tissue",
    "Previous_SourceGroupID",
    "_match_stem_LC25000",
    "LC25000_GroupID",
    "LC25000_LocalCluster",
}


@dataclass(frozen=True)
class Paths:
    preprocessing_dir: Path
    feature_selection_dir: Path
    classical_validation_dir: Path
    output_dir: Path

    @property
    def checkpoint_classical(self) -> Path:
        return self.classical_validation_dir / "Validation_Checkpoint.csv"

    @property
    def checkpoint_dnn(self) -> Path:
        return self.output_dir / "DNN_Validation_Checkpoint.csv"


# =============================================================================
# Reproducibility helpers
# =============================================================================

def set_global_seed(seed: int) -> None:
    """Set Python/NumPy/TensorFlow seeds and request deterministic TF ops."""
    os.environ["PYTHONHASHSEED"] = str(seed)
    random.seed(seed)
    np.random.seed(seed)
    tf.keras.utils.set_random_seed(seed)
    try:
        tf.config.experimental.enable_op_determinism()
    except Exception:
        pass


def json_dump(path: Path, data: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2, default=str),
        encoding="utf-8",
    )


# =============================================================================
# File/data helpers
# =============================================================================

def find_existing_file(folder: Path, stem: str) -> Path:
    candidates = (
        folder / f"{stem}.csv.gz",
        folder / f"{stem}.csv",
        folder / f"{stem}.xlsx",
    )
    for candidate in candidates:
        if candidate.exists():
            return candidate
    raise FileNotFoundError(
        "Could not find any of:\n" + "\n".join(str(p) for p in candidates)
    )


def read_table(path: Path) -> pd.DataFrame:
    suffixes = "".join(path.suffixes).lower()
    if suffixes.endswith(".csv.gz") or path.suffix.lower() == ".csv":
        return pd.read_csv(path)
    if path.suffix.lower() in {".xlsx", ".xlsm", ".xls"}:
        return pd.read_excel(path)
    raise ValueError(f"Unsupported file format: {path}")


def load_feature_names_json(scenario_dir: Path) -> list[str]:
    path = scenario_dir / "Feature_Names.json"
    if not path.exists():
        raise FileNotFoundError(f"Feature_Names.json not found:\n{path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list) or not all(isinstance(x, str) for x in data):
        raise ValueError(f"Feature_Names.json must be a JSON list of strings: {path}")
    names = [x.strip() for x in data]
    if len(names) != len(set(names)):
        raise ValueError(f"Duplicate feature names found in {path}")
    return names


def load_npy_split(
    preprocessing_dir: Path,
    scenario: str,
    split_name: str,
) -> tuple[np.ndarray, pd.DataFrame, list[str]]:
    if split_name not in {"Train", "Validation"}:
        raise ValueError(
            "This program permits only Train and Validation. "
            "Test is intentionally prohibited."
        )

    scenario_dir = preprocessing_dir / scenario
    split_dir = scenario_dir / SOURCE_VARIANT / split_name
    x_path = split_dir / "X.npy"
    metadata_path = split_dir / "Metadata.csv.gz"

    if not x_path.exists():
        raise FileNotFoundError(f"X.npy not found:\n{x_path}")
    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata.csv.gz not found:\n{metadata_path}")

    feature_names = load_feature_names_json(scenario_dir)
    X = np.load(x_path, mmap_mode="r")
    metadata = pd.read_csv(metadata_path)
    metadata.columns = [str(c).strip() for c in metadata.columns]

    if TARGET_COLUMN not in metadata.columns:
        raise KeyError(f"{scenario}/{split_name}: missing metadata column {TARGET_COLUMN!r}")
    if X.ndim != 2:
        raise ValueError(f"{scenario}/{split_name}: X.npy must be 2-D, got shape {X.shape}")
    if X.shape[0] != len(metadata):
        raise ValueError(
            f"{scenario}/{split_name}: row mismatch between X.npy ({X.shape[0]}) "
            f"and Metadata.csv.gz ({len(metadata)})."
        )
    if X.shape[1] != len(feature_names):
        raise ValueError(
            f"{scenario}/{split_name}: feature-count mismatch between X.npy ({X.shape[1]}) "
            f"and Feature_Names.json ({len(feature_names)})."
        )

    return X, metadata, feature_names


def load_standard_split(
    preprocessing_dir: Path,
    scenario: str,
    split_name: str,
) -> pd.DataFrame:
    if split_name not in {"Train", "Validation"}:
        raise ValueError(
            "This program permits only Train and Validation. "
            "Test is intentionally prohibited."
        )

    folder = preprocessing_dir / scenario / SOURCE_VARIANT
    path = find_existing_file(folder, split_name)
    frame = read_table(path)
    frame.columns = [str(c).strip() for c in frame.columns]

    required = {TARGET_COLUMN}
    missing = required.difference(frame.columns)
    if missing:
        raise KeyError(f"{scenario}/{split_name}: missing columns {sorted(missing)}")

    return frame


def read_selected_features(
    feature_selection_dir: Path,
    scenario: str,
    method: str,
    k: int,
) -> list[str]:
    path = (
        feature_selection_dir
        / scenario
        / method
        / f"Selected_Features_K{k:03d}.xlsx"
    )
    if not path.exists():
        raise FileNotFoundError(
            f"Selected feature file does not exist:\n{path}"
        )

    frame = pd.read_excel(path)
    if "Feature" not in frame.columns:
        raise KeyError(f"'Feature' column not found in {path}")

    features = frame["Feature"].dropna().astype(str).str.strip().tolist()
    features = [x for x in features if x]

    if len(features) != k:
        raise ValueError(
            f"{scenario}/{method}/K{k}: selected feature file contains "
            f"{len(features)} features, expected exactly {k}."
        )

    if len(set(features)) != len(features):
        raise ValueError(
            f"{scenario}/{method}/K{k}: duplicate feature names were found."
        )

    return features


def validate_features_exist(
    frame: pd.DataFrame,
    features: list[str],
    context: str,
) -> None:
    missing = sorted(set(features).difference(frame.columns))
    if missing:
        raise KeyError(
            f"{context}: {len(missing)} selected features are absent. "
            f"Examples: {missing[:10]}"
        )


def choose_sample_id_column(frame: pd.DataFrame) -> str | None:
    for column in ("ImageSHA256", "FileName", "ImgName"):
        if column in frame.columns:
            return column
    return None


# =============================================================================
# Candidate feature configurations from classical Pre6 Screening
# =============================================================================

def build_candidate_feature_configs(
    classical_checkpoint: Path,
    top_n: int,
) -> tuple[pd.DataFrame, dict[str, list[tuple[str, int]]]]:
    """
    Select top-N feature configurations per scenario by aggregate Screening
    performance across ALL nine classical models.

    This is a validation-only pre-screening step. Test is not involved.
    """
    if not classical_checkpoint.exists():
        raise FileNotFoundError(
            f"Classical Pre6 checkpoint not found:\n{classical_checkpoint}"
        )

    df = pd.read_csv(classical_checkpoint)

    required = {
        "Stage",
        "Scenario",
        "Feature_Method",
        "K",
        "Model",
        "Status",
        "Validation_Accuracy",
        "Validation_F1_Macro",
    }
    missing = required.difference(df.columns)
    if missing:
        raise KeyError(
            f"Classical checkpoint is missing columns: {sorted(missing)}"
        )

    screening = df[
        df["Stage"].astype(str).str.strip().eq("Screening")
        & df["Status"].astype(str).str.strip().eq("Completed")
        & df["Scenario"].astype(str).str.strip().isin(SCENARIOS)
    ].copy()

    if screening.empty:
        raise RuntimeError("No completed classical Screening rows were found.")

    screening["K"] = pd.to_numeric(screening["K"], errors="raise").astype(int)
    screening["Validation_Accuracy"] = pd.to_numeric(
        screening["Validation_Accuracy"], errors="coerce"
    )
    screening["Validation_F1_Macro"] = pd.to_numeric(
        screening["Validation_F1_Macro"], errors="coerce"
    )

    screening = screening.dropna(
        subset=["Validation_Accuracy", "Validation_F1_Macro"]
    )

    models_present = set(screening["Model"].astype(str).str.strip().unique())
    missing_models = EXPECTED_CLASSICAL_MODELS.difference(models_present)
    if missing_models:
        raise RuntimeError(
            "Classical Screening is incomplete. Missing expected models: "
            + ", ".join(sorted(missing_models))
        )

    rows: list[dict[str, Any]] = []
    selected: dict[str, list[tuple[str, int]]] = {}

    for scenario in SCENARIOS:
        part = screening[
            screening["Scenario"].astype(str).str.strip().eq(scenario)
        ].copy()

        if part.empty:
            raise RuntimeError(f"No Screening rows for scenario: {scenario}")

        grouped = (
            part.groupby(["Feature_Method", "K"], as_index=False)
            .agg(
                Classical_Model_Count=("Model", "nunique"),
                Mean_Screening_Accuracy=("Validation_Accuracy", "mean"),
                Mean_Screening_F1_Macro=("Validation_F1_Macro", "mean"),
                Min_Screening_Accuracy=("Validation_Accuracy", "min"),
                Max_Screening_Accuracy=("Validation_Accuracy", "max"),
            )
        )

        # Only compare configurations evaluated by all expected models.
        grouped = grouped[
            grouped["Classical_Model_Count"] == len(EXPECTED_CLASSICAL_MODELS)
        ].copy()

        if grouped.empty:
            raise RuntimeError(
                f"{scenario}: no feature configuration has complete Screening "
                f"results for all {len(EXPECTED_CLASSICAL_MODELS)} classical models."
            )

        grouped = grouped.sort_values(
            [
                "Mean_Screening_Accuracy",
                "Mean_Screening_F1_Macro",
                "K",
                "Feature_Method",
            ],
            ascending=[False, False, True, True],
            kind="mergesort",
        ).reset_index(drop=True)

        grouped.insert(0, "Scenario", scenario)
        grouped.insert(1, "Aggregate_Rank", np.arange(1, len(grouped) + 1))
        grouped["Selected_For_DNN"] = grouped["Aggregate_Rank"] <= top_n

        top = grouped.head(top_n)
        selected[scenario] = [
            (str(row.Feature_Method), int(row.K))
            for row in top.itertuples(index=False)
        ]

        rows.extend(grouped.to_dict("records"))

    all_candidates = pd.DataFrame(rows)
    return all_candidates, selected


# =============================================================================
# DNN model and metrics
# =============================================================================

def build_dnn(input_dim: int, n_classes: int) -> keras.Model:
    if input_dim <= 0:
        raise ValueError("input_dim must be positive.")
    if n_classes < 2:
        raise ValueError("n_classes must be at least 2.")

    inputs = keras.Input(shape=(input_dim,), name="features")
    x = layers.Dense(
        DENSE_UNITS[0],
        activation="relu",
        kernel_initializer="he_normal",
        name="dense_128",
    )(inputs)
    x = layers.BatchNormalization(name="bn_128")(x)
    x = layers.Dropout(DROPOUT_RATES[0], name="dropout_030")(x)

    x = layers.Dense(
        DENSE_UNITS[1],
        activation="relu",
        kernel_initializer="he_normal",
        name="dense_64",
    )(x)
    x = layers.BatchNormalization(name="bn_64")(x)
    x = layers.Dropout(DROPOUT_RATES[1], name="dropout_020")(x)

    x = layers.Dense(
        DENSE_UNITS[2],
        activation="relu",
        kernel_initializer="he_normal",
        name="dense_32",
    )(x)

    if n_classes == 2:
        outputs = layers.Dense(1, activation="sigmoid", name="output")(x)
        loss = "binary_crossentropy"
    else:
        outputs = layers.Dense(
            n_classes,
            activation="softmax",
            name="output",
        )(x)
        loss = "sparse_categorical_crossentropy"

    model = keras.Model(inputs=inputs, outputs=outputs, name="MC_CRoMD_DNN")

    optimizer = keras.optimizers.Adam(
        learning_rate=INITIAL_LEARNING_RATE
    )

    model.compile(
        optimizer=optimizer,
        loss=loss,
        metrics=[keras.metrics.SparseCategoricalAccuracy(name="accuracy")]
        if n_classes > 2
        else [keras.metrics.BinaryAccuracy(name="accuracy", threshold=0.5)],
    )

    return model


def predict_labels_and_probabilities(
    model: keras.Model,
    X: np.ndarray,
    n_classes: int,
) -> tuple[np.ndarray, np.ndarray]:
    raw = np.asarray(model.predict(X, verbose=0), dtype=float)

    if n_classes == 2:
        positive = raw.reshape(-1)
        probabilities = np.column_stack([1.0 - positive, positive])
        predictions = (positive >= 0.5).astype(int)
    else:
        probabilities = raw
        predictions = np.argmax(probabilities, axis=1).astype(int)

    return predictions, probabilities


def calculate_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    probabilities: np.ndarray,
    n_classes: int,
) -> dict[str, float]:
    metrics = {
        "Validation_Accuracy": float(accuracy_score(y_true, y_pred)),
        "Validation_Precision_Macro": float(
            precision_score(y_true, y_pred, average="macro", zero_division=0)
        ),
        "Validation_Recall_Macro": float(
            recall_score(y_true, y_pred, average="macro", zero_division=0)
        ),
        "Validation_F1_Macro": float(
            f1_score(y_true, y_pred, average="macro", zero_division=0)
        ),
        "Validation_Precision_Weighted": float(
            precision_score(y_true, y_pred, average="weighted", zero_division=0)
        ),
        "Validation_Recall_Weighted": float(
            recall_score(y_true, y_pred, average="weighted", zero_division=0)
        ),
        "Validation_F1_Weighted": float(
            f1_score(y_true, y_pred, average="weighted", zero_division=0)
        ),
    }

    try:
        if n_classes == 2:
            auc_value = roc_auc_score(y_true, probabilities[:, 1])
        else:
            y_bin = label_binarize(y_true, classes=np.arange(n_classes))
            auc_value = roc_auc_score(
                y_bin,
                probabilities,
                average="macro",
                multi_class="ovr",
            )
        metrics["Validation_ROC_AUC_OVR_Macro"] = float(auc_value)
    except Exception:
        metrics["Validation_ROC_AUC_OVR_Macro"] = float("nan")

    return metrics


# =============================================================================
# Checkpoint and run utilities
# =============================================================================

RESULT_COLUMNS = [
    "Run_ID",
    "Scenario",
    "Feature_Method",
    "K",
    "Seed",
    "Train_Rows",
    "Validation_Rows",
    "Feature_Count",
    "Class_Count",
    "Class_Names_JSON",
    "Epochs_Ran",
    "Best_Epoch_By_Val_Loss",
    "Best_Val_Loss",
    "Fit_Seconds",
    "Predict_Seconds",
    "Parameter_Count",
    "Validation_Accuracy",
    "Validation_Precision_Macro",
    "Validation_Recall_Macro",
    "Validation_F1_Macro",
    "Validation_Precision_Weighted",
    "Validation_Recall_Weighted",
    "Validation_F1_Weighted",
    "Validation_ROC_AUC_OVR_Macro",
    "Status",
    "Error",
]


def make_run_id(
    scenario: str,
    method: str,
    k: int,
    seed: int,
) -> str:
    return f"{scenario}|{method}|K{k}|Seed{seed}"


def load_dnn_checkpoint(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame(columns=RESULT_COLUMNS)

    frame = pd.read_csv(path)
    for column in RESULT_COLUMNS:
        if column not in frame.columns:
            frame[column] = np.nan
    return frame[RESULT_COLUMNS]


def save_dnn_checkpoint(frame: pd.DataFrame, path: Path) -> None:
    temp = path.with_name(path.stem + "_TEMP.csv")
    frame.to_csv(temp, index=False)
    temp.replace(path)


def upsert_checkpoint_row(
    checkpoint: pd.DataFrame,
    row: dict[str, Any],
    path: Path,
) -> pd.DataFrame:
    run_id = str(row["Run_ID"])
    checkpoint = checkpoint[
        checkpoint["Run_ID"].astype(str) != run_id
    ].copy()
    checkpoint = pd.concat(
        [checkpoint, pd.DataFrame([row], columns=RESULT_COLUMNS)],
        ignore_index=True,
    )
    save_dnn_checkpoint(checkpoint, path)
    return checkpoint


def completed_run_ids(checkpoint: pd.DataFrame) -> set[str]:
    if checkpoint.empty:
        return set()
    return set(
        checkpoint.loc[
            checkpoint["Status"].astype(str).eq("Completed"),
            "Run_ID",
        ].astype(str)
    )


def time_limit_reached(start_time: float, max_hours: float) -> bool:
    if max_hours <= 0:
        return False
    return (time.perf_counter() - start_time) >= max_hours * 3600.0


# =============================================================================
# One DNN run
# =============================================================================

def run_one_seed(
    *,
    scenario: str,
    method: str,
    k: int,
    seed: int,
    train_frame: pd.DataFrame | None,
    validation_frame: pd.DataFrame | None,
    selected_features: list[str],
    run_dir: Path,
    train_matrix: np.ndarray | None = None,
    validation_matrix: np.ndarray | None = None,
    train_metadata: pd.DataFrame | None = None,
    validation_metadata: pd.DataFrame | None = None,
    feature_names: list[str] | None = None,
) -> dict[str, Any]:
    set_global_seed(seed)
    tf.keras.backend.clear_session()
    gc.collect()

    using_npy = train_matrix is not None

    if using_npy:
        if any(x is None for x in (validation_matrix, train_metadata, validation_metadata, feature_names)):
            raise ValueError("Incomplete NPY-backed inputs for run_one_seed.")
        feature_index = {name: i for i, name in enumerate(feature_names)}
        missing = [f for f in selected_features if f not in feature_index]
        if missing:
            raise KeyError(
                f"{scenario}/{method}/K{k}: {len(missing)} selected features are absent from "
                f"Feature_Names.json. Examples: {missing[:10]}"
            )
        selected_idx = np.asarray([feature_index[f] for f in selected_features], dtype=np.int64)
        label_encoder = LabelEncoder()
        y_train = label_encoder.fit_transform(train_metadata[TARGET_COLUMN].to_numpy())
        y_val = label_encoder.transform(validation_metadata[TARGET_COLUMN].to_numpy())
        X_train = np.asarray(train_matrix[:, selected_idx], dtype=np.float32)
        X_val = np.asarray(validation_matrix[:, selected_idx], dtype=np.float32)
        train_rows = len(train_metadata)
        validation_rows = len(validation_metadata)
        sample_source = validation_metadata
    else:
        if train_frame is None or validation_frame is None:
            raise ValueError("DataFrame-backed inputs are missing.")
        validate_features_exist(
            train_frame,
            selected_features,
            f"{scenario}/{method}/K{k}/Train",
        )
        validate_features_exist(
            validation_frame,
            selected_features,
            f"{scenario}/{method}/K{k}/Validation",
        )
        label_encoder = LabelEncoder()
        y_train = label_encoder.fit_transform(train_frame[TARGET_COLUMN].to_numpy())
        y_val = label_encoder.transform(validation_frame[TARGET_COLUMN].to_numpy())
        X_train = train_frame[selected_features].to_numpy(dtype=np.float32)
        X_val = validation_frame[selected_features].to_numpy(dtype=np.float32)
        train_rows = len(train_frame)
        validation_rows = len(validation_frame)
        sample_source = validation_frame

    classes_train = set(np.unique(y_train))
    classes_val = set(np.unique(y_val))
    if not classes_val.issubset(classes_train):
        raise ValueError(
            f"{scenario}: Validation contains a class absent from Train."
        )

    n_classes = len(label_encoder.classes_)

    if not np.isfinite(X_train).all():
        raise ValueError(
            f"{scenario}/{method}/K{k}: Train contains NaN or infinity "
            "after preprocessing."
        )
    if not np.isfinite(X_val).all():
        raise ValueError(
            f"{scenario}/{method}/K{k}: Validation contains NaN or infinity "
            "after preprocessing."
        )

    run_dir.mkdir(parents=True, exist_ok=True)
    best_model_path = run_dir / "Best_Model.keras"

    model = build_dnn(
        input_dim=len(selected_features),
        n_classes=n_classes,
    )

    callbacks = [
        keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=EARLY_STOPPING_PATIENCE,
            mode="min",
            restore_best_weights=True,
            verbose=1,
        ),
        keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=REDUCE_LR_FACTOR,
            patience=REDUCE_LR_PATIENCE,
            min_lr=MIN_LEARNING_RATE,
            mode="min",
            verbose=1,
        ),
        keras.callbacks.ModelCheckpoint(
            filepath=best_model_path,
            monitor="val_loss",
            mode="min",
            save_best_only=True,
            save_weights_only=False,
            verbose=0,
        ),
        keras.callbacks.TerminateOnNaN(),
    ]

    fit_start = time.perf_counter()
    history = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=MAX_EPOCHS,
        batch_size=BATCH_SIZE,
        shuffle=True,
        callbacks=callbacks,
        verbose=2,
    )
    fit_seconds = time.perf_counter() - fit_start

    # Reload the exact checkpoint with minimum validation loss.
    best_model = keras.models.load_model(best_model_path)

    predict_start = time.perf_counter()
    y_pred, probabilities = predict_labels_and_probabilities(
        best_model,
        X_val,
        n_classes=n_classes,
    )
    predict_seconds = time.perf_counter() - predict_start

    metrics = calculate_metrics(
        y_true=y_val,
        y_pred=y_pred,
        probabilities=probabilities,
        n_classes=n_classes,
    )

    val_losses = np.asarray(history.history["val_loss"], dtype=float)
    best_epoch = int(np.nanargmin(val_losses)) + 1
    best_val_loss = float(np.nanmin(val_losses))

    # Save history.
    history_frame = pd.DataFrame(history.history)
    history_frame.index = np.arange(1, len(history_frame) + 1)
    history_frame.index.name = "Epoch"
    history_frame.to_csv(run_dir / "Training_History.csv")

    # Save confusion matrix counts.
    cm = confusion_matrix(
        y_val,
        y_pred,
        labels=np.arange(n_classes),
    )
    class_names = [str(x) for x in label_encoder.classes_]
    pd.DataFrame(
        cm,
        index=[f"True_{x}" for x in class_names],
        columns=[f"Pred_{x}" for x in class_names],
    ).to_excel(run_dir / "Validation_Confusion_Matrix.xlsx")

    # Save per-sample predictions/probabilities.
    sample_id_column = choose_sample_id_column(sample_source)
    prediction_frame = pd.DataFrame(
        {
            "Row_Index": sample_source.index.to_numpy(),
            "True_Encoded": y_val,
            "Predicted_Encoded": y_pred,
            "True_Label": [class_names[i] for i in y_val],
            "Predicted_Label": [class_names[i] for i in y_pred],
        }
    )
    if sample_id_column is not None:
        prediction_frame.insert(
            1,
            sample_id_column,
            sample_source[sample_id_column].astype(str).to_numpy(),
        )

    for class_index, class_name in enumerate(class_names):
        prediction_frame[f"Probability_{class_name}"] = probabilities[:, class_index]

    prediction_frame.to_csv(
        run_dir / "Validation_Predictions.csv",
        index=False,
    )

    # Save selected feature list.
    pd.DataFrame(
        {
            "Rank": np.arange(1, len(selected_features) + 1),
            "Feature": selected_features,
        }
    ).to_excel(run_dir / "Selected_Features.xlsx", index=False)

    # Save architecture summary.
    lines: list[str] = []
    best_model.summary(print_fn=lines.append)
    (run_dir / "Model_Summary.txt").write_text(
        "\n".join(lines),
        encoding="utf-8",
    )

    model_config = {
        "scenario": scenario,
        "feature_method": method,
        "k": k,
        "seed": seed,
        "source_variant": SOURCE_VARIANT,
        "architecture": {
            "dense_units": list(DENSE_UNITS),
            "activations": ["relu", "relu", "relu"],
            "batch_normalization_after": [128, 64],
            "dropout_rates": list(DROPOUT_RATES),
            "output_units": 1 if n_classes == 2 else n_classes,
            "output_activation": "sigmoid" if n_classes == 2 else "softmax",
            "kernel_initializer": "he_normal",
        },
        "training": {
            "optimizer": "Adam",
            "initial_learning_rate": INITIAL_LEARNING_RATE,
            "loss": (
                "binary_crossentropy"
                if n_classes == 2
                else "sparse_categorical_crossentropy"
            ),
            "batch_size": BATCH_SIZE,
            "max_epochs": MAX_EPOCHS,
            "shuffle": True,
            "early_stopping": {
                "monitor": "val_loss",
                "patience": EARLY_STOPPING_PATIENCE,
                "mode": "min",
                "restore_best_weights": True,
            },
            "reduce_lr_on_plateau": {
                "monitor": "val_loss",
                "factor": REDUCE_LR_FACTOR,
                "patience": REDUCE_LR_PATIENCE,
                "min_lr": MIN_LEARNING_RATE,
                "mode": "min",
            },
            "checkpoint": {
                "monitor": "val_loss",
                "mode": "min",
                "save_best_only": True,
            },
        },
        "class_names": class_names,
        "parameter_count": int(best_model.count_params()),
        "best_epoch_by_val_loss": best_epoch,
        "best_val_loss": best_val_loss,
    }
    json_dump(run_dir / "Run_Metadata.json", model_config)

    result: dict[str, Any] = {
        "Run_ID": make_run_id(scenario, method, k, seed),
        "Scenario": scenario,
        "Feature_Method": method,
        "K": int(k),
        "Seed": int(seed),
        "Train_Rows": int(train_rows),
        "Validation_Rows": int(validation_rows),
        "Feature_Count": int(len(selected_features)),
        "Class_Count": int(n_classes),
        "Class_Names_JSON": json.dumps(class_names, ensure_ascii=False),
        "Epochs_Ran": int(len(history_frame)),
        "Best_Epoch_By_Val_Loss": best_epoch,
        "Best_Val_Loss": best_val_loss,
        "Fit_Seconds": float(fit_seconds),
        "Predict_Seconds": float(predict_seconds),
        "Parameter_Count": int(best_model.count_params()),
        "Status": "Completed",
        "Error": "",
    }
    result.update(metrics)

    del model, best_model, X_train, X_val, y_train, y_val, y_pred, probabilities
    tf.keras.backend.clear_session()
    gc.collect()

    return result


# =============================================================================
# Aggregation and final validation reports
# =============================================================================

def create_validation_reports(
    checkpoint: pd.DataFrame,
    all_candidates: pd.DataFrame,
    selected_candidates: dict[str, list[tuple[str, int]]],
    seeds: tuple[int, ...],
    output_dir: Path,
) -> None:
    completed = checkpoint[
        checkpoint["Status"].astype(str).eq("Completed")
    ].copy()

    if completed.empty:
        return

    # Save raw completed runs.
    completed.sort_values(
        ["Scenario", "Feature_Method", "K", "Seed"]
    ).to_excel(
        output_dir / "All_DNN_Validation_Runs.xlsx",
        index=False,
    )

    expected_run_count = sum(
        len(configs) * len(seeds)
        for configs in selected_candidates.values()
    )

    if len(completed) < expected_run_count:
        # Partial reports are still useful, but do not declare a final best config.
        partial = (
            completed.groupby(
                ["Scenario", "Feature_Method", "K"],
                as_index=False,
            )
            .agg(
                Completed_Seeds=("Seed", "nunique"),
                Mean_Validation_Accuracy=("Validation_Accuracy", "mean"),
                SD_Validation_Accuracy=("Validation_Accuracy", "std"),
                Mean_Validation_F1_Macro=("Validation_F1_Macro", "mean"),
                SD_Validation_F1_Macro=("Validation_F1_Macro", "std"),
            )
        )
        partial.to_excel(
            output_dir / "DNN_Validation_Summary_PARTIAL.xlsx",
            index=False,
        )
        return

    # Require exact prespecified seed set for every selected configuration.
    expected_seed_set = set(seeds)
    for scenario, configs in selected_candidates.items():
        for method, k in configs:
            subset = completed[
                (completed["Scenario"] == scenario)
                & (completed["Feature_Method"] == method)
                & (completed["K"].astype(int) == int(k))
            ]
            got = set(pd.to_numeric(subset["Seed"], errors="coerce").dropna().astype(int))
            if got != expected_seed_set:
                raise RuntimeError(
                    f"Incomplete seed set for {scenario}/{method}/K{k}. "
                    f"Expected {sorted(expected_seed_set)}, got {sorted(got)}."
                )

    summary = (
        completed.groupby(
            ["Scenario", "Feature_Method", "K"],
            as_index=False,
        )
        .agg(
            Seeds=("Seed", "nunique"),
            Mean_Validation_Accuracy=("Validation_Accuracy", "mean"),
            SD_Validation_Accuracy=("Validation_Accuracy", "std"),
            Mean_Validation_Precision_Macro=("Validation_Precision_Macro", "mean"),
            Mean_Validation_Recall_Macro=("Validation_Recall_Macro", "mean"),
            Mean_Validation_F1_Macro=("Validation_F1_Macro", "mean"),
            SD_Validation_F1_Macro=("Validation_F1_Macro", "std"),
            Mean_Validation_F1_Weighted=("Validation_F1_Weighted", "mean"),
            Mean_Validation_ROC_AUC_OVR_Macro=("Validation_ROC_AUC_OVR_Macro", "mean"),
            Mean_Fit_Seconds=("Fit_Seconds", "mean"),
            Mean_Predict_Seconds=("Predict_Seconds", "mean"),
            Mean_Epochs_Ran=("Epochs_Ran", "mean"),
        )
    )

    summary = summary.sort_values(
        [
            "Scenario",
            PRIMARY_SELECTION_METRIC,
            SECONDARY_SELECTION_METRIC,
            "K",
            "Feature_Method",
        ],
        ascending=[True, False, False, True, True],
        kind="mergesort",
    )

    summary.to_excel(
        output_dir / "DNN_Validation_Summary.xlsx",
        index=False,
    )

    best_rows: list[pd.Series] = []
    for scenario in SCENARIOS:
        part = summary[summary["Scenario"] == scenario].copy()
        if part.empty:
            raise RuntimeError(f"No completed DNN summary for {scenario}.")
        best_rows.append(part.iloc[0])

    best = pd.DataFrame(best_rows)
    best.to_excel(
        output_dir / "Best_DNN_Configuration_Per_Scenario.xlsx",
        index=False,
    )

    # Save a compact candidate audit tying classical pre-screening to DNN runs.
    all_candidates.to_excel(
        output_dir / "Classical_Screening_Aggregate_For_DNN.xlsx",
        index=False,
    )


# =============================================================================
# Main
# =============================================================================

def build_paths(base_dir: Path, patch_size: int) -> Paths:
    return Paths(
        preprocessing_dir=base_dir / "3-DataPreprocessing" / str(patch_size),
        feature_selection_dir=base_dir / "4-FeatureSelection" / str(patch_size),
        classical_validation_dir=base_dir / "5-ModelValidation" / str(patch_size),
        output_dir=base_dir / "6-DNNValidation" / str(patch_size),
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Leakage-controlled DNN validation using group-aware Train/Validation only."
        )
    )
    parser.add_argument(
        "--base-dir",
        type=Path,
        default=Path(r"G:\My Research About Lung Canser\INASS"),
    )
    parser.add_argument(
        "--patch-size",
        type=int,
        default=PATCH_SIZE,
        choices=(32, 64, 128, 256),
    )
    parser.add_argument(
        "--top-n",
        type=int,
        default=DEFAULT_TOP_N,
    )
    parser.add_argument(
        "--seeds",
        nargs="+",
        type=int,
        default=list(DEFAULT_SEEDS),
    )
    parser.add_argument(
        "--max-hours",
        type=float,
        default=DEFAULT_MAX_HOURS,
    )

    args, unknown = parser.parse_known_args()
    if unknown:
        print("Ignored unknown arguments:", unknown)

    if args.top_n <= 0:
        raise ValueError("--top-n must be > 0.")
    if args.max_hours < 0:
        raise ValueError("--max-hours cannot be negative.")

    seeds = tuple(dict.fromkeys(int(x) for x in args.seeds))
    if not seeds:
        raise ValueError("At least one seed is required.")

    paths = build_paths(Path(args.base_dir), args.patch_size)

    for required_path, label in (
        (paths.preprocessing_dir, "Pre4 preprocessing directory"),
        (paths.feature_selection_dir, "Pre5 feature-selection directory"),
        (paths.classical_validation_dir, "Classical Pre6 validation directory"),
    ):
        if not required_path.exists():
            raise FileNotFoundError(f"{label} does not exist:\n{required_path}")

    paths.output_dir.mkdir(parents=True, exist_ok=True)

    print("=" * 92)
    print("MC-CRoMD DNN Validation - Leakage-Controlled")
    print("=" * 92)
    print("Patch size             :", args.patch_size)
    print("Preprocessing          :", paths.preprocessing_dir)
    print("Feature selection      :", paths.feature_selection_dir)
    print("Classical checkpoint   :", paths.checkpoint_classical)
    print("DNN output             :", paths.output_dir)
    print("Source variant         :", SOURCE_VARIANT)
    print("Top-N configs/scenario :", args.top_n)
    print("Seeds                  :", seeds)
    print("Maximum launch time    :", args.max_hours, "hours")
    print("IMPORTANT              : Test is NOT loaded or used.")
    print("=" * 92)

    all_candidates, selected_candidates = build_candidate_feature_configs(
        classical_checkpoint=paths.checkpoint_classical,
        top_n=args.top_n,
    )

    all_candidates.to_excel(
        paths.output_dir / "Candidate_Feature_Configurations.xlsx",
        index=False,
    )

    print("\nSelected validation-only DNN candidates:")
    for scenario in SCENARIOS:
        text = ", ".join(
            f"{method}/K{k}"
            for method, k in selected_candidates[scenario]
        )
        print(f"  {scenario:12s}: {text}")

    checkpoint = load_dnn_checkpoint(paths.checkpoint_dnn)
    done = completed_run_ids(checkpoint)

    # Cache Train/Validation inputs per scenario. For patch size 32, use NPY+metadata
    # low-memory storage created by Pre4. Other patch sizes keep the original table loader.
    data_cache: dict[tuple[str, str], Any] = {}
    start_time = time.perf_counter()
    stopped_by_time = False
    runs_this_launch = 0

    for scenario in SCENARIOS:
        if args.patch_size == 32:
            train_matrix, train_metadata, feature_names = load_npy_split(
                paths.preprocessing_dir, scenario, "Train"
            )
            validation_matrix, validation_metadata, validation_feature_names = load_npy_split(
                paths.preprocessing_dir, scenario, "Validation"
            )
            if feature_names != validation_feature_names:
                raise ValueError(f"{scenario}: Train and Validation feature-name lists differ.")
            train_frame = None
            validation_frame = None
        else:
            for split_name in ("Train", "Validation"):
                data_cache[(scenario, split_name)] = load_standard_split(
                    paths.preprocessing_dir,
                    scenario,
                    split_name,
                )
            train_frame = data_cache[(scenario, "Train")]
            validation_frame = data_cache[(scenario, "Validation")]
            train_matrix = validation_matrix = None
            train_metadata = validation_metadata = None
            feature_names = None

        for method, k in selected_candidates[scenario]:
            selected_features = read_selected_features(
                paths.feature_selection_dir,
                scenario,
                method,
                k,
            )

            for seed in seeds:
                run_id = make_run_id(scenario, method, k, seed)

                if run_id in done:
                    print("Skip completed:", run_id)
                    continue

                if time_limit_reached(start_time, args.max_hours):
                    stopped_by_time = True
                    break

                print("\n" + "-" * 92)
                print(
                    f"RUN: {scenario} | {method} | K={k} | Seed={seed}"
                )

                run_dir = (
                    paths.output_dir
                    / "Runs"
                    / scenario
                    / method
                    / f"K{k:05d}"
                    / f"Seed_{seed}"
                )

                row: dict[str, Any] = {
                    "Run_ID": run_id,
                    "Scenario": scenario,
                    "Feature_Method": method,
                    "K": int(k),
                    "Seed": int(seed),
                    "Status": "Failed",
                    "Error": "",
                }

                try:
                    result = run_one_seed(
                        scenario=scenario,
                        method=method,
                        k=k,
                        seed=seed,
                        train_frame=train_frame,
                        validation_frame=validation_frame,
                        selected_features=selected_features,
                        run_dir=run_dir,
                        train_matrix=train_matrix,
                        validation_matrix=validation_matrix,
                        train_metadata=train_metadata,
                        validation_metadata=validation_metadata,
                        feature_names=feature_names,
                    )
                    row.update(result)
                    print(
                        "Completed | "
                        f"Acc={row['Validation_Accuracy']:.6f} | "
                        f"F1macro={row['Validation_F1_Macro']:.6f} | "
                        f"BestEpoch={row['Best_Epoch_By_Val_Loss']}"
                    )
                except Exception as exc:
                    row["Error"] = repr(exc)
                    print("FAILED:", repr(exc))

                checkpoint = upsert_checkpoint_row(
                    checkpoint,
                    row,
                    paths.checkpoint_dnn,
                )
                done = completed_run_ids(checkpoint)
                runs_this_launch += 1

            if stopped_by_time:
                break
        if stopped_by_time:
            break

    create_validation_reports(
        checkpoint=checkpoint,
        all_candidates=all_candidates,
        selected_candidates=selected_candidates,
        seeds=seeds,
        output_dir=paths.output_dir,
    )

    metadata = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "patch_size": args.patch_size,
        "base_dir": str(Path(args.base_dir)),
        "preprocessing_dir": str(paths.preprocessing_dir),
        "feature_selection_dir": str(paths.feature_selection_dir),
        "classical_validation_dir": str(paths.classical_validation_dir),
        "output_dir": str(paths.output_dir),
        "test_policy": (
            "Test is never loaded or used by this program. "
            "Final Test must be evaluated only after all configuration decisions are frozen."
        ),
        "candidate_policy": (
            "Top feature configurations are pre-screened using completed classical-model "
            "Screening results from Validation only; aggregate mean Accuracy across all "
            "nine classical models, then mean Macro-F1, then smaller K."
        ),
        "dnn_selection_policy": (
            "Final DNN configuration per scenario is selected by mean Validation Accuracy "
            "across prespecified seeds, then mean Validation Macro-F1, then smaller K. "
            "No single seed is cherry-picked."
        ),
        "top_n": args.top_n,
        "seeds": list(seeds),
        "source_variant": SOURCE_VARIANT,
        "architecture": {
            "dense_units": list(DENSE_UNITS),
            "batch_normalization_after": [128, 64],
            "dropout_rates": list(DROPOUT_RATES),
            "hidden_activation": "relu",
            "kernel_initializer": "he_normal",
            "binary_output": "1 sigmoid",
            "multiclass_output": "n_classes softmax",
        },
        "training": {
            "optimizer": "Adam",
            "initial_learning_rate": INITIAL_LEARNING_RATE,
            "batch_size": BATCH_SIZE,
            "max_epochs": MAX_EPOCHS,
            "early_stopping_monitor": "val_loss",
            "early_stopping_patience": EARLY_STOPPING_PATIENCE,
            "reduce_lr_factor": REDUCE_LR_FACTOR,
            "reduce_lr_patience": REDUCE_LR_PATIENCE,
            "min_learning_rate": MIN_LEARNING_RATE,
            "checkpoint_monitor": "val_loss",
        },
        "software": {
            "python": platform.python_version(),
            "tensorflow": tf.__version__,
            "keras": getattr(keras, "__version__", "tensorflow.keras"),
            "numpy": np.__version__,
            "pandas": pd.__version__,
            "scikit_learn": sklearn.__version__,
        },
        "runtime": {
            "runs_completed_this_launch": runs_this_launch,
            "elapsed_seconds_this_launch": time.perf_counter() - start_time,
            "stopped_by_time_limit": stopped_by_time,
        },
    }
    json_dump(paths.output_dir / "DNN_Validation_Metadata.json", metadata)

    print("\n" + "=" * 92)
    if stopped_by_time:
        print("TIME LIMIT REACHED SAFELY BETWEEN DNN RUNS.")
        print("Run the SAME command again; completed runs will be skipped.")
    else:
        print("DNN VALIDATION LAUNCH COMPLETE.")
    print("Checkpoint:", paths.checkpoint_dnn)
    print("Output    :", paths.output_dir)
    print("IMPORTANT : Test was not loaded or used.")
    print("=" * 92)


if __name__ == "__main__":
    main()
